version: '3'
services:
  redis-server:
    container_name: 'redis-server'
    image: 'redis'
  node-app:
    container_name: 'express-server'
    restart: on-failure
    build: .
    ports:
      - "8081:8081"