version: '3'
services:
  web:
    container_name: react
    build: .
    ports:
      - "3000:80" # 80 is the default port for nginx
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]