version: '3'
services:
  web:
    container_name: react-ngnix
    build:
      context: .
      dockerfile: Dockerfile  # Production Dockerfile (Nginx)
    ports:
      - "3000:80"  # Map port 3000 (host) to port 80 (Nginx inside container)
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Development Dockerfile (for running tests)
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]